import type { RoutingRule } from "@/lib/model-routing/contract"

/**
 * Deterministic educational routing rules (priority ascending = evaluated first).
 * claimScope is educational_pattern unless product docs are cited.
 */
export const ROUTING_RULES: readonly RoutingRule[] = [
  {
    id: "RR-DET-01",
    name: "Deterministic checklist work",
    priority: 10,
    when: {
      difficulty: { max: 2 },
      risk: { max: 2 },
      judgment: { max: 2 },
      repetition: { min: 3 },
    },
    outcome: {
      taskClass: "deterministic-checklist",
      executor: "script-or-template",
      modelClass: "none",
      verification: "automated-assert / golden-file",
      approvalRequired: false,
      onFailure: "fix-script-then-human-if-repeated",
      rationale: "난이도·위험·판단이 낮고 반복이 높으면 규칙/스크립트가 더 안정적이고 비용이 낮다.",
    },
    claimScope: "educational_pattern",
  },
  {
    id: "RR-RISK-01",
    name: "High risk irreversible change",
    priority: 20,
    when: { risk: { min: 5 }, reversibility: { max: 2 } },
    outcome: {
      taskClass: "high-risk-irreversible",
      executor: "specialist-agent-plus-human",
      modelClass: "frontier",
      verification: "independent-review + staged rollout checklist",
      approvalRequired: true,
      onFailure: "stop-and-escalate-to-human",
      rationale: "비가역·고위험 작업은 고성능 경로보다 승인·독립 검토·중단 권한이 우선이다.",
    },
    claimScope: "educational_pattern",
  },
  {
    id: "RR-RISK-02",
    name: "Elevated risk needs review",
    priority: 30,
    when: { risk: { min: 4 } },
    outcome: {
      taskClass: "elevated-risk",
      executor: "implementer-agent",
      modelClass: "standard",
      verification: "independent-reviewer-agent",
      approvalRequired: true,
      onFailure: "retry-once-then-escalate",
      rationale: "위험이 높으면 구현자와 검토자를 분리하고 사람 승인을 기본으로 둔다.",
    },
    claimScope: "educational_pattern",
  },
  {
    id: "RR-JUDGE-01",
    name: "High judgment policy work",
    priority: 40,
    when: { judgment: { min: 4 }, contextScope: { min: 3 } },
    outcome: {
      taskClass: "judgment-heavy",
      executor: "senior-agent-or-human",
      modelClass: "frontier",
      verification: "rubric + human spot-check",
      approvalRequired: true,
      onFailure: "human-escalation",
      rationale: "정책·경계 판단이 크면 모델 성능만으로 닫지 않고 사람 에스컬레이션을 남긴다.",
    },
    claimScope: "educational_pattern",
  },
  {
    id: "RR-COST-01",
    name: "High repetition prefers cheaper path",
    priority: 50,
    when: { repetition: { min: 4 }, risk: { max: 3 }, difficulty: { max: 3 } },
    outcome: {
      taskClass: "repetitive-implementation",
      executor: "cheap-agent-or-script",
      modelClass: "cheap",
      verification: "sample-spot-check + tests",
      approvalRequired: false,
      onFailure: "upgrade-to-standard-model-once",
      rationale: "반복 작업에 항상 최고 성능 경로를 쓰면 교육적으로도 운영적으로도 낭비가 생긴다.",
    },
    claimScope: "educational_pattern",
  },
  {
    id: "RR-CTX-01",
    name: "Wide context needs structured handoff",
    priority: 60,
    when: { contextScope: { min: 4 }, difficulty: { min: 3 } },
    outcome: {
      taskClass: "wide-context-build",
      executor: "orchestrated-subagents",
      modelClass: "standard",
      verification: "integration-tests + summary review",
      approvalRequired: false,
      onFailure: "narrow-scope-and-retry",
      rationale: "문맥이 넓으면 한 번에 맡기기보다 분해·핸드오프·통합 검증이 필요하다.",
    },
    claimScope: "educational_pattern",
  },
  {
    id: "RR-STD-01",
    name: "Default general implementation",
    priority: 100,
    when: {},
    outcome: {
      taskClass: "general-implementation",
      executor: "standard-agent",
      modelClass: "standard",
      verification: "unit-tests + self-check + optional peer review",
      approvalRequired: false,
      onFailure: "retry-with-stronger-verification",
      rationale: "특수 조건이 없으면 표준 실행 경로와 테스트 검증으로 충분하다.",
    },
    claimScope: "educational_pattern",
  },
] as const
