import type { RoutingScenario } from "@/lib/model-routing/contract"

export const ROUTING_SCENARIOS: readonly RoutingScenario[] = [
  {
    id: "sc-rename-file",
    title: "파일명 일괄 변경",
    summary: "정해진 규칙으로 여러 파일 이름을 바꾼다. 롤백이 쉽다.",
    axes: {
      difficulty: 1,
      risk: 1,
      repetition: 5,
      judgment: 1,
      contextScope: 1,
      reversibility: 5,
    },
    learningFocus: ["Task Classification", "Cost-Aware"],
    expectedPrimaryRuleId: "RR-DET-01",
  },
  {
    id: "sc-frontmatter",
    title: "Frontmatter 필드 채우기",
    summary: "템플릿이 있는 메타데이터 필드를 채운다.",
    axes: {
      difficulty: 2,
      risk: 1,
      repetition: 4,
      judgment: 1,
      contextScope: 2,
      reversibility: 5,
    },
    learningFocus: ["Task Routing", "Script vs AI"],
    expectedPrimaryRuleId: "RR-DET-01",
  },
  {
    id: "sc-format-lint",
    title: "포맷·린트 수정",
    summary: "자동 수정 가능한 스타일 위반을 고친다.",
    axes: {
      difficulty: 1,
      risk: 2,
      repetition: 5,
      judgment: 1,
      contextScope: 2,
      reversibility: 5,
    },
    learningFocus: ["Executor Routing"],
    expectedPrimaryRuleId: "RR-DET-01",
  },
  {
    id: "sc-ui-tweak",
    title: "작은 UI 수정",
    summary: "버튼 위치와 여백을 조정한다. 테스트로 회귀를 볼 수 있다.",
    axes: {
      difficulty: 3,
      risk: 2,
      repetition: 2,
      judgment: 2,
      contextScope: 3,
      reversibility: 4,
    },
    learningFocus: ["Model Routing", "Standard path"],
    expectedPrimaryRuleId: "RR-STD-01",
  },
  {
    id: "sc-bugfix",
    title: "재현 가능한 버그 수정",
    summary: "실패 테스트가 있는 버그를 고친다.",
    axes: {
      difficulty: 3,
      risk: 3,
      repetition: 2,
      judgment: 2,
      contextScope: 3,
      reversibility: 4,
    },
    learningFocus: ["Evaluation & Retry"],
    expectedPrimaryRuleId: "RR-STD-01",
  },
  {
    id: "sc-feature",
    title: "일반 기능 구현",
    summary: "기존 패턴을 따르는 중간 규모 기능.",
    axes: {
      difficulty: 3,
      risk: 3,
      repetition: 2,
      judgment: 3,
      contextScope: 3,
      reversibility: 4,
    },
    learningFocus: ["Executor + Model"],
    expectedPrimaryRuleId: "RR-STD-01",
  },
  {
    id: "sc-api-design",
    title: "API 설계",
    summary: "공개 계약과 호환성을 고려한 인터페이스 설계.",
    axes: {
      difficulty: 4,
      risk: 3,
      repetition: 1,
      judgment: 4,
      contextScope: 4,
      reversibility: 3,
    },
    learningFocus: ["Judgment", "Context"],
    expectedPrimaryRuleId: "RR-JUDGE-01",
  },
  {
    id: "sc-auth",
    title: "인증 구조 변경",
    summary: "로그인·세션 경계를 건드린다. 보안 민감.",
    axes: {
      difficulty: 4,
      risk: 5,
      repetition: 1,
      judgment: 4,
      contextScope: 4,
      reversibility: 2,
    },
    learningFocus: ["Human Escalation", "Independent Review"],
    expectedPrimaryRuleId: "RR-RISK-01",
  },
  {
    id: "sc-db",
    title: "DB 스키마 변경",
    summary: "마이그레이션이 필요한 데이터 구조 변경.",
    axes: {
      difficulty: 4,
      risk: 5,
      repetition: 1,
      judgment: 4,
      contextScope: 4,
      reversibility: 1,
    },
    learningFocus: ["Approval", "Irreversibility"],
    expectedPrimaryRuleId: "RR-RISK-01",
  },
  {
    id: "sc-deploy",
    title: "프로덕션 배포 실행",
    summary: "실제 사용자 트래픽 환경에 반영한다.",
    axes: {
      difficulty: 3,
      risk: 5,
      repetition: 2,
      judgment: 3,
      contextScope: 3,
      reversibility: 2,
    },
    learningFocus: ["Human Approval"],
    expectedPrimaryRuleId: "RR-RISK-01",
  },
  {
    id: "sc-security",
    title: "보안 검토 대응",
    summary: "취약점 수정과 검증 계획을 세운다.",
    axes: {
      difficulty: 4,
      risk: 5,
      repetition: 1,
      judgment: 5,
      contextScope: 4,
      reversibility: 2,
    },
    learningFocus: ["Review separation"],
    expectedPrimaryRuleId: "RR-RISK-01",
  },
  {
    id: "sc-refactor",
    title: "대규모 리팩토링",
    summary: "동작 유지하며 구조를 넓게 재배치한다.",
    axes: {
      difficulty: 4,
      risk: 4,
      repetition: 1,
      judgment: 3,
      contextScope: 5,
      reversibility: 3,
    },
    learningFocus: ["Wide context", "Validation"],
    expectedPrimaryRuleId: "RR-RISK-02",
  },
  {
    id: "sc-research",
    title: "문서·출처 조사",
    summary: "공식 문서를 모아 주장의 근거를 정리한다.",
    axes: {
      difficulty: 3,
      risk: 2,
      repetition: 2,
      judgment: 3,
      contextScope: 4,
      reversibility: 5,
    },
    learningFocus: ["Routing Observability of claims"],
    expectedPrimaryRuleId: "RR-CTX-01",
  },
  {
    id: "sc-final-qa",
    title: "최종 QA 게이트",
    summary: "릴리스 전 기계 검사와 표본 검토를 수행한다.",
    axes: {
      difficulty: 3,
      risk: 3,
      repetition: 3,
      judgment: 3,
      contextScope: 3,
      reversibility: 4,
    },
    learningFocus: ["Evaluation", "Observability"],
    expectedPrimaryRuleId: "RR-STD-01",
  },
] as const
