import type { CurriculumModule, LessonMeta } from "@/content/schema"

export const CURRICULUM_MODULES = [
  {
    id: "getting-started",
    order: 1,
    title: "시작하기",
    description: "AI 바이브코딩을 공부하는 목적, 사이트 사용법, 설명형 학습 루틴을 잡습니다.",
    goal: "학습자가 개발과 AI를 다시 배울 준비를 갖춘다.",
  },
  {
    id: "development-basics",
    order: 2,
    title: "개발 기초",
    description: "프로그램, 파일, 폴더, 변수, 조건문, 함수, 오류를 생활 언어로 연결합니다.",
    goal: "코드가 제품 행동을 만드는 과정을 설명할 수 있다.",
  },
  {
    id: "web-basics",
    order: 3,
    title: "웹 개발 기초",
    description: "HTML, CSS, JavaScript, 브라우저, 요청과 응답을 화면 중심으로 배웁니다.",
    goal: "웹 화면의 뼈대, 스타일, 행동을 분리해서 이해한다.",
  },
  {
    id: "frontend-frameworks",
    order: 4,
    title: "프론트엔드 프레임워크",
    description: "React, TypeScript, Next.js가 왜 등장했는지와 컴포넌트 사고를 익힙니다.",
    goal: "화면을 재사용 가능한 조각으로 설계할 수 있다.",
  },
  {
    id: "git-collaboration",
    order: 5,
    title: "Git & 협업",
    description: "버전 기록, 브랜치, 리뷰, 되돌리기, 협업 흐름을 학습합니다.",
    goal: "작업 이력을 안전하게 남기고 공유할 수 있다.",
  },
  {
    id: "data-backend",
    order: 6,
    title: "데이터와 백엔드",
    description: "API, DB, 인증, 상태 코드, 서버가 제품 기능을 지탱하는 방식을 배웁니다.",
    goal: "화면 뒤에서 데이터가 오가는 경로를 설명할 수 있다.",
  },
  {
    id: "deployment-ops",
    order: 7,
    title: "배포와 운영",
    description: "빌드, 배포, 환경 변수, 로그, 모니터링, 장애 대응의 기본을 다룹니다.",
    goal: "내 컴퓨터의 코드가 사용자에게 도달하는 과정을 이해한다.",
  },
  {
    id: "ai-basics",
    order: 8,
    title: "AI 활용 기초",
    description: "프롬프트, 맥락, 예시, 검증, 반복 개선의 기본기를 배웁니다.",
    goal: "AI에게 좋은 작업 지시를 만들고 결과를 검증한다.",
  },
  {
    id: "ai-coding-tools",
    order: 9,
    title: "AI 코딩 도구",
    description: "ChatGPT, Codex, IDE 에이전트, 코드 리뷰 도구의 역할과 한계를 익힙니다.",
    goal: "도구를 믿는 대신 검증하며 협업한다.",
  },
  {
    id: "ai-system-design",
    order: 10,
    title: "AI 시스템 설계",
    description: "Context Engineering, MCP, Skills, Workflow, Agent 구조를 순서대로 학습합니다.",
    goal: "AI 기능을 일회성 프롬프트가 아니라 시스템으로 설계한다.",
  },
  {
    id: "practical-vibe-coding",
    order: 11,
    title: "실전 바이브코딩",
    description: "요구사항 정리, 작업 분해, 구현, 검증, 리팩터링 루틴을 연습합니다.",
    goal: "AI와 함께 작은 제품 기능을 끝까지 완성한다.",
  },
  {
    id: "explanation-practice",
    order: 12,
    title: "설명 연습",
    description: "개념을 남에게 설명하는 훈련, 면접식 질문, 비유 만들기를 반복합니다.",
    goal: "알고 있는 것을 말로 구조화한다.",
  },
  {
    id: "project-textbook",
    order: 13,
    title: "실전 프로젝트 교재",
    description: "SaaS, 관리자 도구, AI 챗봇, 자동화 워크플로를 프로젝트형으로 연결합니다.",
    goal: "개념을 묶어 실제 서비스 설계로 확장한다.",
  },
] satisfies readonly CurriculumModule[]

export const LESSON_META = [
  {
    slug: "ai-vibe-coding-orientation",
    moduleId: "getting-started",
    order: 1,
    title: "AI 바이브코딩이란 무엇인가",
    summary: "AI와 함께 개발을 배우는 태도, 한계, 검증 루틴을 먼저 잡습니다.",
    level: "입문",
    type: "deep-dive",
    minutes: 35,
    tags: ["AI", "학습법", "바이브코딩"],
  },
  {
    slug: "web-screen-anatomy",
    moduleId: "web-basics",
    order: 2,
    title: "웹 화면은 어떻게 만들어지는가",
    summary: "HTML, CSS, JavaScript가 화면의 뼈대, 옷, 행동을 나누어 맡는 구조를 배웁니다.",
    level: "입문",
    type: "deep-dive",
    minutes: 40,
    tags: ["HTML", "CSS", "JavaScript", "브라우저"],
  },
  {
    slug: "typescript-react-nextjs",
    moduleId: "frontend-frameworks",
    order: 3,
    title: "TypeScript, React, Next.js는 왜 함께 쓰는가",
    summary: "타입 안전성, 컴포넌트, 라우팅이 복잡한 프론트엔드를 어떻게 정리하는지 봅니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 45,
    tags: ["TypeScript", "React", "Next.js", "컴포넌트"],
  },
  {
    slug: "git-collaboration-basics",
    moduleId: "git-collaboration",
    order: 4,
    title: "Git은 왜 개발자의 타임머신인가",
    summary: "commit, branch, merge, pull request를 협업과 복구 관점에서 배웁니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 35,
    tags: ["Git", "협업", "브랜치", "PR"],
  },
  {
    slug: "api-db-backend-flow",
    moduleId: "data-backend",
    order: 5,
    title: "API와 DB는 제품 뒤에서 무엇을 하는가",
    summary: "요청, 응답, 상태 코드, 데이터 저장소가 사용자 행동과 연결되는 흐름을 배웁니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 45,
    tags: ["API", "DB", "백엔드", "HTTP"],
  },
  {
    slug: "from-prompt-to-system",
    moduleId: "ai-system-design",
    order: 1,
    title: "프롬프트에서 시스템으로",
    summary:
      "일회성 프롬프트의 한계를 이해하고, 컨텍스트·도구·루프·검증을 갖춘 AI 시스템 설계로 확장합니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 55,
    tags: ["AI 시스템 설계", "Context Engineering", "Workflow", "Agent"],
  },
  {
    slug: "context-engineering-basics",
    moduleId: "ai-system-design",
    order: 2,
    title: "Context Engineering 기초: AI가 판단할 재료 설계",
    summary:
      "AI가 추론할 때 받는 정보 묶음을 목표, 제약, 근거, 도구 결과로 선별하고 유지하는 방법을 배웁니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 55,
    tags: ["Context Engineering", "컨텍스트", "AI 시스템 설계", "에이전트"],
  },
  {
    slug: "context-window-and-memory",
    moduleId: "ai-system-design",
    order: 3,
    title: "컨텍스트 윈도와 메모리 관리",
    summary:
      "컨텍스트 창의 한계, 토큰 누적, context rot, compaction과 상태 산출물로 긴 AI 작업을 유지하는 법을 배웁니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 55,
    tags: ["Context Window", "Context Engineering", "메모리 관리", "Compaction"],
  },
  {
    slug: "system-prompts-and-instruction-layers",
    moduleId: "ai-system-design",
    order: 4,
    title: "시스템 프롬프트와 지침 계층",
    summary:
      "시스템 프롬프트, 사용자 메시지, 도구 정의, 예시가 함께 컨텍스트를 이루는 방식을 배우고 명확한 지침 설계법을 익힙니다.",
    level: "기초",
    type: "deep-dive",
    minutes: 55,
    tags: ["System Prompt", "Instruction", "Context Engineering", "도구 정의"],
  },
  {
    slug: "ai-workflow-design",
    moduleId: "ai-system-design",
    order: 5,
    title: "AI Workflow 설계: 단계 분해와 품질 게이트",
    summary:
      "Workflow와 Agent의 차이를 구분하고, AI 작업을 단계와 품질 게이트로 나누어 예측 가능하게 만드는 방법을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 60,
    tags: ["Workflow", "Agent", "품질 게이트", "AI 시스템 설계"],
  },
  {
    slug: "context-engineering-mcp-skills",
    moduleId: "ai-system-design",
    order: 6,
    title: "Context Engineering, MCP, Skills의 관계",
    summary:
      "AI가 일을 잘하게 만드는 정보 상태, 외부 연결 표준, 재사용 절차를 구분해 시스템 관점에서 이해합니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 60,
    tags: ["Context Engineering", "MCP", "Skills", "AI 시스템 설계"],
  },
  {
    slug: "tool-calling-basics",
    moduleId: "ai-system-design",
    order: 7,
    title: "Tool Calling: AI가 도구를 부르는 방식",
    summary:
      "AI가 외부 함수나 도구를 구조화된 호출 요청으로 선택하고, 애플리케이션이 실행하는 경계를 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 55,
    tags: ["Tool Calling", "Function Calling", "API", "AI 도구"],
  },
  {
    slug: "rag-fundamentals",
    moduleId: "ai-system-design",
    order: 8,
    title: "RAG: 모델이 모르는 것을 알려주는 방법",
    summary:
      "검색된 외부 지식을 모델 입력에 넣어 최신 정보와 도메인 지식에 근거한 답변을 만드는 흐름을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 55,
    tags: ["RAG", "Retrieval", "Embedding", "Context Engineering"],
  },
  {
    slug: "mcp-architecture-basics",
    moduleId: "ai-system-design",
    order: 9,
    title: "MCP 구조: 서버, 클라이언트, 도구, 리소스",
    summary:
      "MCP의 host, client, server 구조와 tools, resources의 차이를 배우고 Tool Calling과의 관계를 정리합니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 60,
    tags: ["MCP", "Tool Calling", "Resources", "AI 시스템 설계"],
  },
  {
    slug: "designing-reusable-skills",
    moduleId: "ai-system-design",
    order: 10,
    title: "Skill 설계: 재사용 절차 만들기",
    summary:
      "반복되는 AI 작업 절차를 SKILL.md, description, supporting files로 패키징하고 컨텍스트 비용과 신뢰 경계를 함께 설계하는 법을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 60,
    tags: ["Skills", "SKILL.md", "Progressive Disclosure", "AI 시스템 설계"],
  },
  {
    slug: "agent-loop-anatomy",
    moduleId: "ai-system-design",
    order: 11,
    title: "Agent의 구조: 도구 루프와 관찰-행동 사이클",
    summary:
      "Agent Loop가 평가, 도구 호출, 결과 반영, 반복으로 움직이는 구조를 배우고 Tool Calling과의 차이를 정리합니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 60,
    tags: ["Agent", "Agent Loop", "Tool Calling", "도구 루프"],
  },
  {
    slug: "subagents-and-delegation",
    moduleId: "ai-system-design",
    order: 12,
    title: "SubAgent와 위임 패턴",
    summary:
      "SubAgent를 별도 컨텍스트, 권한, 도구 제한, 결과 계약으로 이해하고 main agent가 무엇을 위임해야 하는지 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 65,
    tags: ["SubAgent", "Delegation", "Context Engineering", "Agent"],
  },
  {
    slug: "multi-agent-orchestration",
    moduleId: "ai-system-design",
    order: 13,
    title: "Orchestration: 여러 Agent의 협업 설계",
    summary:
      "Handoff와 agents-as-tools를 기준으로 여러 specialist agent의 소유권, 라우팅, 최종 답변 책임을 설계하는 법을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 65,
    tags: ["Orchestration", "Handoff", "Agents as Tools", "AI 시스템 설계"],
  },
  {
    slug: "loop-engineering-basics",
    moduleId: "ai-system-design",
    order: 14,
    title: "Loop Engineering: 반복 실행과 종료 조건",
    summary:
      "Agent loop를 turn, tool result, 권한, 비용, context, hook, 종료 조건으로 나누어 반복 실행을 통제하는 방법을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 70,
    tags: ["Loop Engineering", "Agent Loop", "Hooks", "AI 시스템 설계"],
  },
  {
    slug: "harness-engineering-basics",
    moduleId: "ai-system-design",
    order: 15,
    title: "Harness Engineering: 실행 환경, 권한, 검증 장치",
    summary:
      "Agent 실행의 control plane과 execution plane을 나누고 sandbox, guardrails, hooks, traces, eval harness로 결과를 통제하는 법을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 70,
    tags: ["Harness Engineering", "Sandbox", "Guardrails", "Observability"],
  },
  {
    slug: "context-caching-and-state",
    moduleId: "ai-system-design",
    order: 16,
    title: "Context Caching과 상태 재사용",
    summary:
      "Prompt caching을 memory가 아니라 반복 prefix 재사용으로 이해하고, stable content와 dynamic context를 나누어 비용과 지연을 줄이는 법을 배웁니다.",
    level: "중급",
    type: "deep-dive",
    minutes: 65,
    tags: ["Context Caching", "Prompt Caching", "Context Engineering", "AI 시스템 설계"],
  },
  {
    slug: "ai-system-evaluation",
    moduleId: "ai-system-design",
    order: 17,
    title: "AI 시스템 평가와 eval 레퍼런스",
    summary:
      "AI 시스템 품질을 success criteria, traces, graders, datasets, outcomes, runtime resource budget으로 평가하는 방법을 정리합니다.",
    level: "중급",
    type: "reference",
    minutes: 70,
    tags: ["AI Evaluation", "Evals", "Trace Grading", "Agent"],
  },
] satisfies readonly LessonMeta[]
